version: "3"

services:
  redis:
    build: .
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local